##### Indexing and Selecting of Numpy Arrays

In [1]:
import numpy as np

In [4]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[8]

8

In [9]:
arr[1:5]

array([1, 2, 3, 4])

In [10]:
arr[:5]

array([0, 1, 2, 3, 4])

In [11]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [12]:
arr_2d = np.array([[5,4,8],[55,2,9],[25,44,15]])

In [13]:
arr_2d

array([[ 5,  4,  8],
       [55,  2,  9],
       [25, 44, 15]])

In [17]:
# DOUPLE BRACKET NOTATION: First bracket is rows and second bracket is column
arr_2d[0][2]

8

In [18]:
# SINGLE BRACKET NOTATION: 

arr_2d[0,2]

8

In [19]:
arr_2d

array([[ 5,  4,  8],
       [55,  2,  9],
       [25, 44, 15]])

In [22]:
# If you want to get everything in specific column.
arr_2d[:,2:]

array([[ 8],
       [ 9],
       [15]])

In [25]:
# If you want to get a specific row.
arr_2d[1:2]

array([[55,  2,  9]])

##### Conditional selection

In [26]:
arr1 = np.arange(1,11)

In [27]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
bool_array = arr1 > 5 # Checks if the condition is met by returning true og false

In [30]:
bool_array

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [31]:
arr1[bool_array] # Here I am returning all the TRUE values after the condion.

array([ 6,  7,  8,  9, 10])

In [32]:
arr1[arr1>5] # Shorter and better version

array([ 6,  7,  8,  9, 10])

In [36]:
my_array = np.arange(1,101).reshape(10,10)

In [37]:
my_array

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [41]:
my_array[:,9:]

array([[ 10],
       [ 20],
       [ 30],
       [ 40],
       [ 50],
       [ 60],
       [ 70],
       [ 80],
       [ 90],
       [100]])

In [50]:
my_array[4,4]

45