In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [8]:
my_list2 =[ [1,2,3],  [4,5,6],  [7,8,9]]


In [10]:
arr2 = np.array(my_list2)

In [11]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [17]:
np.zeros(3)

array([0., 0., 0.])

In [18]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [65]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [66]:
# The Identity matrix: is useful when dealing with linear algebra problems.
# Number of rows is equal to number of columns and the diagnal is ones and everything else is zeros.

np.eye(4) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [67]:
np.random.rand(5)

array([0.14052146, 0.70304881, 0.40586336, 0.42864325, 0.18313369])

In [68]:
np.random.randn(5)

array([ 0.51927325,  2.28766021,  2.11402435,  0.47285266, -0.71747403])

In [70]:
new_arr = np.random.randint(1,100,10)
new_arr

array([18, 25, 74, 41, 41, 93, 51, 69, 99, 43])

In [71]:
new_arr.max()

99

In [72]:
new_arr.min()


18

In [73]:
# To get index location of the value

new_arr.argmax()


8

In [74]:
new_arr.argmin()


0

In [79]:
new_arr.shape

(10,)